### ISSUE TITLE
Build and Test failures

### ISSUE THREAD

**Issue by ericaddison** [dhale/jtk#26]
@chrisengelsma 

Hi Chris! I just downloaded and built the project, but I ran into three problems along the way:

1) I got a gradle error from the "distributions" block in core/build.gradle. I removed the block and it resolved the error.

2) I got a gradle error in the "signing" block in core/build.gradle. I removed the block and it resolved the error.

3) My test in `ProjectorTest.testAutoLinear()` FAILED! The `new` call should not have the axis scale specified.

I have almost ZERO experience with gradle, so the first two issues could just be my ignorance showing. The test should be fixed so that it passes...

**Comment by chrisengelsma** [comment]
I wouldn't worry about the two build blocks not running, unless you want to create a signed jar.

**Comment by chrisengelsma** [comment]
If you run 'gradle jar ' I believe it doesn't run those processes
